version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - GIN_MODE=release
    secrets:
      - firebase_credentials
    env_file:
      - .env
secrets:
  firebase_credentials:
    file: packages/auth/wherenext-24624-firebase-adminsdk-accountkey.json
